---
- name: Run systemctl daemon-reload
  ansible.builtin.systemd_service:
    daemon_reload: true
- name: Enable timer
  ansible.builtin.systemd_service:
    enabled: true
    name: "{{ motd_service_name }}.timer"
- name: Start timer
  ansible.builtin.systemd_service:
    name: "{{ motd_service_name }}.timer"
    state: started
- name: Restart timer
  ansible.builtin.systemd_service:
    name: "{{ motd_service_name }}.timer"
    state: restarted
